### PR TITLE
Added Ubuntu 16.04 Installation Bash Script

### PR DESCRIPTION
**Pull request by rmsander**
Hello vizdoom team,

Thank you for all your contributions to this package - I'm currently using it for some reinforcement learning research in my lab at school and the API for it has been tremendously helpful.  

I created an installation script (linux_install/install_doom.sh) that automates the installation process for Linux (Ubuntu 16.04, specifically) that you describe in doc/Building.md.  I have also directed users to this script when reading doc/Building.md.  

Please reach out with any questions/comments regarding this PR!  Thank you!

### CODE REVIEW

**Comment by Miffyli** [comment]
Thank you for the kind words :).

I see the script does quite a bit more than just install ViZDoom and its dependencies: It attempts to modify conda envs, installs/uninstalls Julia and uses the pypi version of ViZDoom. A `scripts/linux_check_dependencies.sh` (a script that installs dependencies) could be an useful shortcut, I do not think we need special scripts for installing Python version as it is just `pip install .` once source is cloned.

**Comment by rmsander** [comment]
Sounds great!  I've updated my commits to reflect this - please reach out with further questions/comments!

**Comment by Miffyli** [comment]
Sorry if I was not clear enough: I think the script should not do anything else than install dependencies for building/running ViZDoom on Linux for Python, i.e. no Julia-stuff. Also the two apt-get commands seem to have duplicate packages in them.

**Comment by rmsander** [comment]
No worries!  Apologies for misinterpreting that.  Please let know if my new commit addresses this issue.  Thanks!

**Comment by Miffyli** [comment]
Just two more nitpicks, after which things look good:
* There is no need for `USERNAME` anymore.
* Update README to clarify this file is for Python dependencies, specifically. You can place this after the line before dependencies, i.e.:
> To get all dependencies (except JDK) on Ubuntu execute the following commands in the shell (requires root access). `scripts/linux_check_dependencies.sh` installs these for Python3:

**Comment by rmsander** [comment]
Done!  Please let me know if there are any other changes you'd like me to make.  Thanks!

**Pull request merged**
