### PR TITLE
add walls, floors/ceilings to label buffer

### PR DESCRIPTION
**Pull request by bradyz**
This is a small modification I've added for a past project that uses semantic segmentation in ViZDoom.

We implemented full semantic segmentation,
where every pixel had a label such as pickup/enemy/other/walls/floor/ceiling,
and this was the only change to the C++ backend necessary.

This is definitely a hack at best,
but it worked well enough and wanted some advice on how to properly implement this.

image

### CODE REVIEW

**Comment by mwydmuch** [comment]
Hi @bradyz, thank you for a nice feature, this whole project is mostly one big hack for Dooms engine, so your way of implementing this is totally fine for me :)
I will upgrade it a little by adding walls/floor/ceiling/sky on the labels list later this week.

**Comment by bradyz** [comment]
Awesome! I was worried that there would be label collisions though, like if an object (med kit, enemy) was assigned the label 1 or 0 (walls, floors).

Is this a potential problem?

**Comment by mwydmuch** [comment]
Yes, if the number of objects will exceed 128, then some object will collide with label 1. In most cases, this number is lower, so it's not a big deal. But that's why I plan to add walls/floors to the labels list - to reserve values for them.

**Comment by TolgaDaSilva** [comment]
Is there a way to label corridor and ceiling separately?
I'm trying to detect free space.

**Comment by Miffyli** [comment]
It is not immediately clear how this could be done based on the hacks in this PR, but @mwydmuch did mention he has plans to (eventually) include _everything_ in the labels buffer. I figure he also has better idea how this could be done ^^.

For a flat map you could do a very dirty hack and classify floor/ceil labels below specific height (y coordinate on image) as "floor" and above it "ceiling". This _should_ work for flat maps, but you need to find the threshold first.

**Comment by TolgaDaSilva** [comment]
Thank you for the quick reply. 

There is also a problem with the segmentation on the deathmatch map. The lava line on the floor is detected as a wall.

**Comment by TolgaDaSilva** [comment]
This is how i actually label floor and ceiling, but it's a very slow implementation.

```python
    def dirty(label, pitch):
        tresh = label.shape[0] // 2
        offset = math.floor(pitch * -tresh / 32)

        tmp = np.stack([label] * 3, -1)

        for y in range(label.shape[0]):
            for x in range(label.shape[1]):
                # Walls ~ blue
                if label[y, x] == 0:
                    tmp[y, x] = [255, 0, 0]
                # Ceiling ~ red
                elif label[y, x] == 1 and y < tresh + offset:
                    tmp[y, x] = [0, 0, 255]
                # Floor ~ green
                elif label[y, x] == 1 and y >= tresh + offset:
                    tmp[y, x] = [0, 255, 0]
        return tmp
```

**Pull request merged**
