### PR TITLE
Fix installation in python error when it could not find binaries on Mac

### PR DESCRIPTION
**Pull request by syzer**

### CODE REVIEW

**Comment by mwydmuch** [comment]
Thank you @syzer !

**Comment by syzer** [comment]
@mwydmuch great work man!
Did you think about ading ViZDoom to OpenAi Gym as environment?

**Comment by mwydmuch** [comment]
Thanks @syzer!
There's an official wrapper for OpanAI Gym (https://github.com/openai/doom-py) and it's listed as the environment, however, it's a little bit outdated.

**Comment by syzer** [comment]
:D thanks!
Two years outdated

**Pull request merged**
