### PR TITLE
Update gym version to 0.26

### PR DESCRIPTION
**Pull request by ldfrancis**
Update `gym_wrapper`  to be compatible with the newly released version 0.26. 
Release note - https://github.com/openai/gym/pull/3056

Changes made here include;
1. Use of the new step API
2. Update the render; setting the render_mode on instantiation
3. Always return `info` on reset
4. Update the tests to conform to the new API

@pseudo-rnd-thoughts

### CODE REVIEW

**Comment by pseudo-rnd-thoughts** [comment]
Hi, as one of the gym maintainers, this PR correctly implements the changes from v26.

**Comment by mwydmuch** [comment]
Hi @ldfrancis, thank you very much for PR, and thank you @pseudo-rnd-thoughts for the comment. This looks good. But I have a quick question: the test returns a lot of warnings like this:
```
[...]/gym/utils/env_checker.py:277: UserWarning: WARN: The environment (<OrderEnforcing<PassiveEnvChecker<VizdoomScenarioEnv<VizdoomBasic-v0>>>>) 
is different from the unwrapped version (<VizdoomScenarioEnv<VizdoomBasic-v0>>). 
This could effect the environment checker as the environment most likely has a wrapper applied to it. 
We recommend using the raw environment for `check_env` using `env.unwrapped`.
```
Is that all right in this case? Or can something be improved?

**Comment by ldfrancis** [comment]
Thanks @mwydmuch 
We get the warning because `gym.make` automatically wraps the environment with the `PassiveEnvChecker` and `OrderEnforcing` wrappers. However, the `check_env`  function that checks if an environment respects the gym API prefers the unwrapped environment and logs a warning when given a wrapped environment. There are possible cases where an unwrapped environment which does not respect the gym API is made compatible using wrappers, and we can ignore the warnings. But here we need to pass in the unwrapped environment since it was updated to respect the new API

@pseudo-rnd-thoughts I'd make the update

**Review by mwydmuch — APPROVED** [review]

**Comment by mwydmuch** [comment]
Thank you, @ldfrancis and @pseudo-rnd-thoughts, for the explanation and the change, merging it!

**Pull request merged**
