### PR TITLE
Updated build & transitioning away from python2

### LINKED ISSUE #394: fatal error: arith.h: No such file or directory
Hello, I would like to build vizdoom from source and use c++ bindings.
I have installed all dependencies listed in guide. Im using ubuntu 18.04.

I get this error when using make command:
`[ 62%] Building CXX object src/vizdoom/src/CMakeFiles/vizdoom.dir/zstrformat.cpp.o
In file included from /home/maris/src/ViZDoom/src/vizdoom/src/zstrformat.cpp:93:
/home/maris/src/ViZDoom/src/vizdoom/src/../gdtoa/gdtoa.h:67:10: fatal error: arith.h: No such file or directory
 #include "arith.h"
          ^~~~~~~~~
compilation terminated.
`

From what I understand arith.h is generated by arithchk.c, so this might fail, but im not sure how to test it.
Im using gcc-8 and g++-8

### PR DESCRIPTION
**Pull request by hadjilucasL**
ViZDoom would not compile on a fresh installation of Ubuntu 16.04/18.04 due an error as in Issue #394 

This was because the gdtoa lib include files (that are autogenerated when the gdtoa library is built) are needed by the main ViZDoom source but not included in the main project. This is addressed by the changes in this pull request by modifiying [src/vizdoom/gdtoa/CMakeLists.txt](https://github.com/hadjilucasL/ViZDoom/blob/51a970299ed57d23896e7ce9699f946b401142aa/src/vizdoom/gdtoa/CMakeLists.txt#L44) to expose `arith.h`.

I have also added the configurations needed to move the `./bin` directory outside of its fixed location inside the source root. As is standard when compiling a project with CMake, the user creates a build directory and then generates and compiles the project in there, not within the source directory. The `bin` directory is now inside the CMake build dir. Have also updated the documentation where necessary.

I also started slowly transitioning things towards a python3 codebcase. I think this will simplify a lot of things and make it easier to maintain moving forward (but open to other suggestions).

Anaconda was also not really tested on Travis so also wondering if it will simplify things to keep the instructions just vanilla python3 virtualenv setup.

Resolves #394

### CODE REVIEW

**Comment by Miffyli** [comment]
Does the issue raise from e.g. from newer versions of gcc (as discussed in #394), or something else? I have not had trouble compiling ViZDoom on fresh-ish installations of various Ubuntu (or generally Debian-based) distributions, although I have not done one in a while. 

Python2 removal is welcome, but already being worked on an [another branch](https://github.com/mwydmuch/ViZDoom/tree/python2_removal), so I am not sure if it should be included here :)

**Comment by hadjilucasL** [comment]
The issue arises from the cmake configuration for gdtoa...See changes here: https://github.com/mwydmuch/ViZDoom/pull/439/files#diff-1abdc3ec31fb8fc24bedd2b92d242e26

If you don't expose the files generated (arith.h) then when trying to compile vizdoom code it fails on missing dependencies. 

I tried compiling a couple of times on fresh ubuntu installs (16.04 & 18.04) following your installation guide and on both occasions failed with the arith.h error.  My guess is in your case you probably have arith.h included from a system installed library.

It's also bad practise to build inside in the same location as your cmake sources ... This PR also covers that aspect ... so essentially you can build inside any folder, not just in a hardwired `./bin` folder on the source root.

Re python 3 compatibility... I just updated travis to bionic image (18.05) as that's probably what most people would use now and setup.py to compile the library with the updated cmake config but can revert some of those changes if needed.

**Comment by mwydmuch** [comment]
Hi @hadjilucasL, thank you very much for the pull request, I like the changes you described here, I will test it this week

**Comment by mwydmuch** [comment]
I had to fix setup.py , but other than that, I really like this pull request, thank you @hadjilucasL

**Comment by mwydmuch** [comment]
Actually, I had to temporarily remove "build" directory from setup.py, cause I couldn't make it work for all CMake versions...

**Comment by hadjilucasL** [comment]
Hey @mwydmuch! Glad you found this useful. Apologies about the incompleteness of setup.py... I think i blazed through that part and didn't test it thoroughly. If you haven't gotten it to work as expected I can have another go at it over the weekend.

**Comment by mwydmuch** [comment]
No problem @hadjilucasL, actually this issue was not that easy to spot. I found it after merging and testing on a few different machines with different CMakes. I'm surprised, something seems to behave inconsistently between CMake 3.13+ and older versions. 

To be able to use `build` directory for CMake 3.13+ you need to add `-C build` to `make` in this line:
https://github.com/mwydmuch/ViZDoom/blob/2cf7a5dc1a058a3e61a322e9af1b2cfba9cf80e0/setup.py#L102

But this breaks building for older CMakes. It seems that a `Makefile` is generated in different locations. For sure, I will investigate this later, but if you have any idea how to fix this let me now.

**Comment by Miffyli** [comment]
@mwydmuch While it compiles, it seems like there are some additional trouble with this (see #443).

**Pull request merged**
